name: Ink! CI
on:
  push:
    branches:
      - "**"
    paths:
      - "**.rs"
      - "**.toml"
      - "**.ts"
      - "**.js"
      - ".github/workflows/ink-ci.yml"
      - "**.json"
      - "**.yaml"

  pull_request:
    branches:
      - "**"
    paths:
      - "**.rs"
      - "**.toml"
      - "**.ts"
      - "**.js"
      - ".github/workflows/ink-ci.yml"
      - "**.json"
      - "**.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          components: rustfmt

      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./contracts/psp34/Cargo.toml --all
  
  compile:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          components: rust-src
          target: wasm32-unknown-unknown

      - name: Install binaryen
        run: |
          sudo apt-get update
          sudo apt-get install -y binaryen
      
      - name: Install dylint
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-dylint dylint-link
      
      - name: Install contract
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-contract --force --locked
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build
        run: pnpm compile psp34
      
  test:
    runs-on: ubuntu-latest
    needs: [compile]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          components: rust-src
          target: wasm32-unknown-unknown

      - name: Install binaryen
        run: |
          sudo apt-get update
          sudo apt-get install -y binaryen
      
      - name: Install dylint
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-dylint dylint-link
      
      - name: Install contract
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-contract --force --locked
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Compile & Copy
        run: |
          pnpm compile psp34
          find ./artifacts/ -type f -name "psp34.*" -exec cp {} ./artifacts/ \;
      
      - name: Test
        run: |
          pnpm node > node.log 2>&1 &
          pnpm test psp34
